api = "0.4"

[buildpack]
  id = "laraboot-buildpacks/laraboot-commander"
  name = "laraboot-commander"
  version = "0.0.1"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]

  default_version = "0.0.1"
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/package.sh"