name: 'Create Buildpack'

description: |
  Creates a buildpack
inputs:
  name:
    description: 'The name of the buildpack'
    required: true
  version:
    description: 'Semantic version'
    default: '1.0.0'
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - id: build
      shell: bash
      run: |
        go build -ldflags="-s -w" -o ./bin/detect ./cmd/detect/main.go &&
        go build -ldflags="-s -w" -o ./bin/build ./cmd/build/main.go
    - id: package
      shell: bash
      run: |
        b=$(mktemp -d)
        pack buildpack new "${{ inputs.name }}" -V "${{ inputs.version }}" -p $b
        cp $b/buildpack.toml .
        pack buildpack package dist/${{ inputs.name }}.cnb --config ./package.toml --format file