name: 'Create Buildpack'

description: |
  Creates a buildpack
inputs:
  name:
    description: 'The name of the release'
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - id: random-number-generator
      shell: bash
      run: |
        go build -ldflags="-s -w" -o ./bin/detect ./cmd/detect/main.go &&
        go build -ldflags="-s -w" -o ./bin/build ./cmd/build/main.go &&
        pack buildpack package "$WORKSPACE_DIR/dist/laraboot-commander.cnb" --config ./package.toml --format file