name: 'Create Buildpack'

description: |
  Creates a buildpack
inputs:
  name:
    description: 'The name of the release'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--name"
    - ${{ inputs.name }}