on:
  push:
    branches:
      - dev
      - next
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main

name: run tests
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: buildpacks/github-actions/setup-pack@v4.1.0
        with:
          pack-version: 0.20.0

      - name: Build
        run: make ci

      - name: Gh action
        uses: ./actions/commander
        with:
          name: my-buildpack
          version: 0.0.2
          file: commander.example.yml

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest] #, macos-latest, windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup laraboot CLI
        uses: laraboot-io/github-actions/setup-cli@cli-actions
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
        with:
          pack-version: 0.20.0
      - name: Make binaries
        env:
          GOOS: linux
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          sudo chmod +x ./scripts/package.sh
          ./scripts/package.sh
      - name: Integration test
        run: make tests